[package]
name = "tui-logger"
version = "0.1.8"
authors = ["Jochen Kiemes <jochen@kiemes.de>"]
license = "MIT"
description = "Logger with smart widget for the `tui` crate"
documentation = "https://docs.rs/tui-logger/0.1.8/tui_logger/"
repository = "https://github.com/gin66/tui-logger"
keywords = ["tui", "log", "logger", "widget", "dispatcher"]

[dependencies]
log = "0.4"
chrono = "0.4" 
tui = "0.2"
termion = "1.5"
lazy_static = "1.0"
fxhash = "0.2"
parking_lot = "0.5"
